# version: "3.7"
version: "2.3"
services:
  nd013-c1-vision-starter:
    runtime: nvidia
    build:
      context: ../build/
      dockerfile: Dockerfile

    network_mode: host

    ports:
      - "80:80"

    expose:
      - 443
      - 80

    init: true
    privileged: true

    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - UDEV=1
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace

      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker.sock

      # Enable GUI environments
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

      # Enable kernel modules
      - /lib/modules:/lib/modules

      # Enable creating/reading inside docker new devices
      - /dev:/dev

    # Add devices to be share in container
    devices:

      # NVIDIA drivers to use OpenGL, etc...
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/input:/dev/input
      - /dev/snd:/dev/snd
    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.

    command: "sleep infinity"
